// Simple service definition for Mangle deductive databases.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: mangle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A query request consists of a query and an optional set of
// declarations and rule definitions ("program").
type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A query is a Mangle atom expression like `person(X, Y, /foo)`.
	// An atom is a predicate applied to variables and constants.
	// Examples: `foo(42)`, `foo(X)`, `person(X, Y, /foo)`.
	// The predicate can either refer to the publicly accessible
	// relations of the Mangle DDB, or alternatively to the
	// relations defined in a program that is part of the request.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// A program is a set of declarations and Mangle rule definitions
	// that defines additional relations. The server is free to use
	// any evaluation strategy to compute the needed tuples in these
	// relations, as long as the overall query is evaluated according
	// to Mangle semantics.
	Program string `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mangle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_mangle_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

// An update request consists of fact and rule definitions
// (a "program"). The program will be evaluated on top of
// the current state.
type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// See QueryRequest for what a program is.
	Program string `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mangle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_mangle_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

// List of errors encountered during query and program processing.
// If errors is non-empty, then the answers should not be
// considered complete.
type QueryError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A human-readable error message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *QueryError) Reset() {
	*x = QueryError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mangle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryError) ProtoMessage() {}

func (x *QueryError) ProtoReflect() protoreflect.Message {
	mi := &file_mangle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryError.ProtoReflect.Descriptor instead.
func (*QueryError) Descriptor() ([]byte, []int) {
	return file_mangle_proto_rawDescGZIP(), []int{2}
}

func (x *QueryError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// List of errors encountered during update program processing.
type UpdateError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A human-readable error message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateError) Reset() {
	*x = UpdateError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mangle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateError) ProtoMessage() {}

func (x *UpdateError) ProtoReflect() protoreflect.Message {
	mi := &file_mangle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateError.ProtoReflect.Descriptor instead.
func (*UpdateError) Descriptor() ([]byte, []int) {
	return file_mangle_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// One answer tuple for a given query and optional program.
type QueryAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// For a correct query and optional program, the list of results.
	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *QueryAnswer) Reset() {
	*x = QueryAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mangle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAnswer) ProtoMessage() {}

func (x *QueryAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_mangle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAnswer.ProtoReflect.Descriptor instead.
func (*QueryAnswer) Descriptor() ([]byte, []int) {
	return file_mangle_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// For a successful update, info about updated predicates.
type UpdateAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// For a correct update program, lists updated predicates.
	UpdatedPredicates []string `protobuf:"bytes,2,rep,name=updated_predicates,json=updatedPredicates,proto3" json:"updated_predicates,omitempty"`
}

func (x *UpdateAnswer) Reset() {
	*x = UpdateAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mangle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnswer) ProtoMessage() {}

func (x *UpdateAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_mangle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnswer.ProtoReflect.Descriptor instead.
func (*UpdateAnswer) Descriptor() ([]byte, []int) {
	return file_mangle_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAnswer) GetUpdatedPredicates() []string {
	if x != nil {
		return x.UpdatedPredicates
	}
	return nil
}

var File_mangle_proto protoreflect.FileDescriptor

var file_mangle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x3e, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x29, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x22, 0x1e, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x1f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x25, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x3d, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x12, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x32, 0x75, 0x0a, 0x06, 0x4d, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x2e, 0x6d, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42,
	0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75,
	0x72, 0x61, 0x6b, 0x65, 0x6d, 0x69, 0x72, 0x2f, 0x6d, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mangle_proto_rawDescOnce sync.Once
	file_mangle_proto_rawDescData = file_mangle_proto_rawDesc
)

func file_mangle_proto_rawDescGZIP() []byte {
	file_mangle_proto_rawDescOnce.Do(func() {
		file_mangle_proto_rawDescData = protoimpl.X.CompressGZIP(file_mangle_proto_rawDescData)
	})
	return file_mangle_proto_rawDescData
}

var file_mangle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mangle_proto_goTypes = []interface{}{
	(*QueryRequest)(nil),  // 0: mangle.QueryRequest
	(*UpdateRequest)(nil), // 1: mangle.UpdateRequest
	(*QueryError)(nil),    // 2: mangle.QueryError
	(*UpdateError)(nil),   // 3: mangle.UpdateError
	(*QueryAnswer)(nil),   // 4: mangle.QueryAnswer
	(*UpdateAnswer)(nil),  // 5: mangle.UpdateAnswer
}
var file_mangle_proto_depIdxs = []int32{
	0, // 0: mangle.Mangle.Query:input_type -> mangle.QueryRequest
	1, // 1: mangle.Mangle.Update:input_type -> mangle.UpdateRequest
	4, // 2: mangle.Mangle.Query:output_type -> mangle.QueryAnswer
	5, // 3: mangle.Mangle.Update:output_type -> mangle.UpdateAnswer
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mangle_proto_init() }
func file_mangle_proto_init() {
	if File_mangle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mangle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mangle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mangle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mangle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mangle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mangle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mangle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mangle_proto_goTypes,
		DependencyIndexes: file_mangle_proto_depIdxs,
		MessageInfos:      file_mangle_proto_msgTypes,
	}.Build()
	File_mangle_proto = out.File
	file_mangle_proto_rawDesc = nil
	file_mangle_proto_goTypes = nil
	file_mangle_proto_depIdxs = nil
}
